---
title: "Importing from to tRNAdb and mitotRNAdb as GRanges"
author: "Felix G.M. Ernst"
date: "`r Sys.Date()`"
package: tRNAdbImport
abstract: >
  Example of importing tRNAdb output as GRanges
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
    df_print: paged
vignette: >
  %\VignetteIndexEntry{tRNAdbImport}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown(css.files = c('custom.css'))
```

# Introduction

The tRNAdb and mttRNAdb [@Juehling.2009] is a compilation of tRNA sequences and 
tRNA genes. It is a follow up version of the database of Sprinzl et al. 
[@Sprinzl.2005].

Using `tRNAdbImport` the tRNAdb can be accessed as outlined on the website 
[`r tRNAdbImport::TRNA_DB_URL`](`r tRNAdbImport::TRNA_DB_URL`) and the results
are returned as a `GRanges` object.

# Importing as GRanges

```{r}
library(tRNAdbImport)
# accessing tRNAdb
# tRNA from yeast for Alanine and Phenylalanine
gr <- import.tRNAdb(organism = "Saccharomyces cerevisiae",
              aminoacids = c("Phe","Ala"))
# get a Phenylalanine tRNA from yeast
gr <- import.tRNAdb.id(tdbID = gr[gr$tRNA_type == "Phe",][1]$tRNA_dbID)
# find the same tRNA via blast
gr <- import.tRNAdb.blast(blastSeq = gr$tRNA_seq)

# accessing mtRNAdb
# get the mitochrondrial tRNA for Alanine in Bos taurus
gr <- import.mttRNAdb(organism = "Bos taurus", 
                      aminoacids = "Ala")
# get one mitochrondrial tRNA in Bos taurus. 
gr <- import.mttRNAdb.id(mtdbID = gr[1]$tRNA_dbID)

# check that the result has the appropriate columns
istRNAdbGRanges(gr)
```

# Session info

```{r}
sessionInfo()
```

# References
